language: java
sudo: false

install: true

script: mvn clean package -DskipTests=true

deploy:
  provider: heroku
  api_key:
    secure: "cyD3d/IPrQ9+A616jHblwVkdX17xU9SmBXF4Lb39Gxbpb2cTBi00QuoW80gVfQicGLlZbUwbnbDR5meOczAf55C0D2/dJpzdhsJPPS15k+2explbxGaZECyhFYxZWcct9Cxi1rr+5T6vf9xp0z8625VcSOCgL4a5KR+FkzEHni+SsP71/KCIB2JljC6p2OY6Tew3I5lsQWKx
      w1eRnC6IlQD38SeaVEGnDApkhQWCD83jIvyaVv+Xf6RaX4IZ6Pj0k5RqTNRIBOoANwt+oW4N607cedMkPncAYW1K3kN3xfI8LtCGdzkuWb9764bbXTowOqBaNVU6+xDB8GxD/N1f/e23xvo2T72nWEA7IHIBZJd7fZdzDQE3jqnq7+TUj5aAT7JseOnWqsx/XdUyQpYIEkois069COVbGXv
      8d4nXSgrj/eSwl0WzM5ELgEE/yL4Lmtmpey9uo0vr8COt1XUah6JQUFVXFxgJym8x8c7DN+A7Vj96+Zi4p4toyX5lAe+0DFUI8UWpLBWfVdt0fSSF+XoOTONeXiP0wVjh4juPrCJLgQWTvnwTj8c15v5rQIuESiFZeE7XdOEmzf2O8NUy0FoQDgVDWqm6BYBMdtvaackqO5ttz3ALSGeLJ3
      YRNfB/jmQqcjgLqK+ZXz6bi83q44ib08sO95LaySuFKqkkh3U="
  app: radiant-forest-56815

notifications:
  email:
    recipients:
      -parsentev@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always