language: java
sudo: false

install: true

script: mvn clean package -DskipTests=true

deploy:
  provider: heroku
  api_key:
    secure: 90317be7-f059-484d-a7aa-82a2bddb2227

notifications:
  email:
    recipients:
      -parsentev@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always