language: java
sudo: false

install: true

script: mvn clean package -DskipTests=true

deploy:
  provider: heroku
  api_key:
    secure: iIJFqrlgKqd/tzoW3fG5jptflnUndrM9ivwm74Co2O1+hUvfrXhjEoWdwCF2osSprYatGF2nc6wTCepgjRAuay6mwsKOPzaduQECAoliO2+xAZ9hfabPq1hYA4uTXEZzFLMGoBFTNmFYsL4O5ypfwP9Q4gI1T47n1w/JLDbNhcF5Qh+Sn2n2Qfasd/KCqAMnZGQ42xavHQbPsLA85h7dB0gq5t07Xv7CnYUvWegBXSVQ2MG5CRNnBQza+Im9L9VOF7dq7LydbA0q8lQ1fEhFkpXdf4EuFU7zL3Iu/X3mk8MbuLkW2cqa0xuofFD1eoZzDfp4b2xc26U+GmLG7KDDgv0olHT8dbErQpmTEojK5+ny0PZ3eoAIX1RArDCwuvsgwlxg7/jXWUNcJQpATbwVk9YRktqrJqcBrHHj2pa7TBitOZ/hOfBb9MJqukY3sAzvjMOCReJyNmp0z3zPXoVAQMnFjmFDTEtHSi/ojslYSKQ9kavif7tqxQNV+g4WiOPAkIQGlDkOUWXm6BiBhFkVpXVNwyTJhN0W+KYH5AdDmcgq3z8JsERZnrcHZ+JKRYtJFwRZRCU+nbDb9CwTNq6X9DSZ5PrmvYyKjNoB12J3GyDKj8kqs5+S23Aavb4wq/qUK2q2cDtV78xI1O1+C5XE8J670N7LTOvJaJWyGML/KcU=

notifications:
  email:
    recipients:
      -parsentev@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always