language: java
sudo: false
install: true
script: mvn clean package -DskipTests=true
notifications:
  email:
    recipients: "-parsentev@yandex.ru"
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: nE6hrz7x84Yr448HemoRq8qVicuNW1VPxpexwqyEODblNqx1qXhes9bLRdSOmnNz33U9f4cM48YVTs7UvwwZ4FEwA8fu7H44iXjU+v6PDAiG+YKHoC+UJCphZEd1ImOWHjEvXTkbmZtr03kwQPPVYd7CFaxMyswGw4gzgoRQbr36SRfAU8/CcL7fU4UGfGx4GYoJNgLkzsTkcqz+hAFslHkv/3oyh6vhOgkDzkvOlfKuMbyypxmmzZ0svTGi4JUu4PL4Qt2SP5OVLOfGT7P5Zbqq5vZnYFWCFy/wB5xLSy19Xvg5Ts5hmJoXcp1bbWsnJPg8S5kNLt1n727tA5dX68Rtf5vRTFP6aT8O2FKawZ4ozpaPuQq+WmChv0cxbMmV5uGMXNp4rPolTRuKFlv+RB5VbY9SR31eH0xYAErzdXqWjC4VSPz9SjqsjIXJsAV/2129RwLJXfdIYUPDCvJxE/MZOuVoAm7YMvL0C+9dlj/zKNwcXwATRRou2ZeDxuU7i585TC/AxntZsnn7HqYi8Zg91O+P7rp1oocuwKwm9tyPhXykCWuzzMWh+EAYlKjvBuhSaXnXZSoPpBIy87oQQkSaegaIx1sVcCBDcXGlg+2eCkps3QmYebRbp4AQrDfmJUy82jyv02OeZCGzIDyOstcvhfeuG2kuTxtufiyET8I=
  app: radiant-forest-56815