language: java
sudo: false

install: true

script: mvn clean package -DskipTests=true

deploy:
  provider: heroku
  api_key:
    secure: QzLIJpcgGC4coShcfqW0Un925w3O6hS9uKO8afRXk9XasX29BMjIyF8ZZG8zjzDy0Kghvh6p0S1bNiXpaCEFKgYR78vi8nYzcYEQm6VvC/7xCvUsR0DqMwX54c0gjPqn7Ll/GhlmYWha8eh7hdvU+lwQS9ijUhoirnIu1l6gSVLIMIIxe+k5Hy94AWTK616teD6+2TZjBPRs3h4ug17KrsDJ6REm6T/Sxfek+pgfgQx7hU/CMXlkiIADhIn4bL78y/3FZ0cV1ukj7AKy93t7DHlDgxVqevzGhLhqlszpDu/1ibgZyRZNC+5a2NqoWkOiCkOMlWR0RkDtPrB1SvHUW2vRCeioMCwIPXCyWLB5kwjVHEXRvyQhOQ49NzvvimtDZ6brJvcTGYe1ivg7kkFqsXL9HBAwXYG0osTESK1AGeU0HzecQp48N9THLnZHxUK8+R+fgNvd9kGGrXFLeeMcQhlH/mF3iDmEnRx1Oo0b3omkOmJbo76WXRda8nCxo51rGTG9W3/z4C54ZbrdbewXUV//tJ9j7aRv0fgND6W5aNuUnmtS5nnPvdDHYa0jTDrJIlH2ZX5WxntEAUJRZCDr/Ur7uhXNFPeLA6PPI8L9HCP8PyHMLfAhHlFvELLglmHPGvK+aKNsvlhwXC+asBeSaWbKMMkecPByieK/81XpgkU=
  app: radiant-forest-56815

notifications:
  email:
    recipients:
      -parsentev@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always